spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account_db?useSSL=false&serverTimezone=UTC
    username: domypetito
    password: prova1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

checkers:
  tag: info

server:
  port: 8081 


